baseurl = "http://scottgallant.github.io/deploy-test"
contact = "/:filename/"
languagecode = "en-us"
pluralizelisttitles = false
title = "Bashaw United Church"
[[menu.main]]
name = "Sermonsx wowo"
url = "/sermon"
weight = 1
[[menu.main]]
name = "Events"
url = "/event"
weight = 2
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
