baseurl = "https://uparky.com"
contact = "/:filename/"
languagecode = "en-us"
title = "Bashaw Test Site"
[[menu.main]]
name = "Sermons"
url = "/sermon"
weight = 1
[[menu.main]]
name = "Events"
url = "/event"
weight = 2
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
[taxonomies]
tag = "tags"
